#!/bin/sh

#
# Extract revision
#
if [ -z ${GIT_DIR} ] ; then GIT_DIR=${PWD} ; fi

rev=`git rev-parse --short HEAD`

#
# Update the key
#
if [ -z ${ETCD_CTL+x} ] ; then ETCD_CTL=etcdctl ; fi
if [ -z ${ETCD_BASE+x} ] ; then ETCD_BASE=/git-tracker ; fi

echo -n "etcd:${ETCD_BASE} -> "
${ETCD_CTL} set ${ETCD_BASE} ${rev}
